name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger build on push to main branch
  pull_request:
    branches:
      - main  # Trigger build on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Define the OS for the runner

    steps:
    - name: Check out the code
      uses: actions/checkout@v2  # Checkout the code from your repository

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Set your Java version (change if needed)
        distribution: 'adoptopenjdk'  # Specify the JDK distribution (can also use 'zulu', 'amazon-corretto', etc.)

    - name: Build with Maven
      run: mvn clean install -DskipTests=true  # Build the project

    - name: Run tests
      run: mvn test  # Run unit tests (optional, but recommended)
