name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger build on push to main branch
  pull_request:
    branches:
      - main  # Trigger build on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Define the OS for the runner

    steps:
    - name: Check out the code
      uses: actions/checkout@v2  # Checkout the code from your repository

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'  # Set your Java version (change if needed)
        distribution: 'temurin'  # Use 'temurin' for AdoptOpenJDK builds

    - name: Build with Maven
      working-directory: ./server  # Specify the correct directory (e.g., `backend`)
      run: mvn clean install -DskipTests=true  # Build the project

    - name: Run tests
      working-directory: ./server  # Run tests in the same directory
      run: mvn test  # Run unit tests (optional, but recommended)
